### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by FredericJacobs** [nguyenhuy/AsyncMessagesViewController#2]
Hey @nguyenhuy!

Terrific project. I'm excited. I've been thinking for some time now to build something similar but never managed to find time to actually write it, so congrats to you.

Do you have a public roadmap or contributor guidelines?

**Comment by nguyenhuy** [comment]
Hey @FredericJacobs, thanks for reaching out. I'm really sorry for this late response, definitely unacceptable! Won't happen again.

I haven't focused much on this project lately, but I have an important improvement under construction. It adds support to ASDK latest features, most noticeably the Box model layout system. I will publish the code and create tickets for known issues/improvements within next week. Hopefully this project will get some traffic! Working alone is not so fun :)

Regarding contributor guidelines, I don't have a clear idea at the moment. I will make a simple document next week. But basically any PR/issue report/feedback is very welcome.

So, please stay tuned and let me know if there is anything I can help regarding this project, or any other OSS ones.

P/S: terrific OSS contributions yourself! Really excited to have a chance to talk to you :)

**Comment by FredericJacobs** [comment]
I have iOS9/Xcode7/Swift 2.0 support for the code on master if that's something you're interested in.

**Comment by nguyenhuy** [comment]
Of course, please open up a PR :)

**Comment by nguyenhuy** [comment]
@FredericJacobs I've pushed my latest improvements as well as the contribution guidelines. The roadmap, in the form of GitHub issues, will be created soon. I have to filter out the TODO list I'm keeping privately (some items look quite ridiculous now).

With that, I'm gonna close this ticket. Please create a new one if you have any other question/request/feedback. Cheers!
