### ISSUE TITLE
avatar image

### ISSUE THREAD

**Issue by vcotric** [nguyenhuy/AsyncMessagesViewController#5]
Is is posiible to have avatar image under the message bubble. Thanks

**Comment by nguyenhuy** [comment]
Currently there is no elegant way to support a different layout for message nodes, but you can always subclass `MessageCellNode` and override `-layoutSpecThatFits:` ([here](https://github.com/nguyenhuy/AsyncMessagesViewController/blob/master/Source/Views/MessageCellNode.swift#L67)).

**Comment by vcotric** [comment]
thanks :)

**Comment by nguyenhuy** [comment]
You are welcome! Let me know if you have any questions, whether they are related to AsyncMessagesViewController, or AsyncDisplayKit (FYI, I'm pretty active on that project as well), or anything really. I will do my best to help.

Happy holidays!
