### ISSUE TITLE
dude the example is not building

### ISSUE THREAD

**Issue by yarodevuci** [nguyenhuy/AsyncMessagesViewController#9]
@nguyenhuy 
The example is SO outdated....
Clearly showing that this library is useless.. 
OMG I waisted time to fix errors, and in the end got error with .some lPods not found...

You are worst programmer ever!!!

**Comment by nguyenhuy** [comment]
Yeah, it's been a while since I worked on this repo and the example is admittedly outdated. I'm committed to try to allocate more time for NMessenger and this library in the near future, ~~thanks partially to your insults and harassments in both repos~~. 

Cheers!

P/S: I think you meant "worst"

**Comment by cuongthai** [comment]
Keep up your good works dude (y)

**Comment by yarodevuci** [comment]
@nguyenhuy I did not wont to harass you at all, but a good programmer is always on top their work. You could at least update Read me File.

@cuongthai I don't see any good work at all

**Comment by cuongthai** [comment]
You can't always good at everything my friend. At least he prioritizes his time on contributing on the community and move on. If someone has time why dont just help him instead?

**Comment by yarodevuci** [comment]
@cuongthai I wish I could. I don't have that amount of knowledge. Anyway I need a good Chat UI library. Could not find a good one.

**Comment by cuongthai** [comment]
https://github.com/jessesquires/JSQMessagesViewController
You must have known this? Isnt it fit your needs?

**Comment by yarodevuci** [comment]
@cuongthai 
I use this currently, but it's so buggy and old. I am looking for something modern. JSQ is perfect functionality but very laggy:(
